"""initial schema

Revision ID: e32a093a2292
Revises: 
Create Date: 2026-03-26 20:36:30.066643

"""
from alembic import op
import sqlalchemy as sa


revision = 'e32a093a2292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_factura_doc_mes_anio', 'facturas', ['doc', 'mes', 'anio'])
    op.drop_index(op.f('ix_retiros_doc'), table_name='retiros')
    op.create_index(op.f('ix_retiros_doc'), 'retiros', ['doc'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retiros_doc'), table_name='retiros')
    op.create_index(op.f('ix_retiros_doc'), 'retiros', ['doc'], unique=False)
    op.drop_constraint('uq_factura_doc_mes_anio', 'facturas', type_='unique')
    # ### end Alembic commands ###
